// Lista estática com 180 séries (60 por bloco) e 9 opções de escolha.
// Gerado usando um universo de 39 símbolos para maior variedade.
// A posição dos símbolos corretos é aleatória.

// Função para embaralhar um array (necessária para o helper de sorteio)
const shuffle = (arr) => {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

export const N2_SEQUENCES = [
  // ====================================================================================================
  // BLOCO 1: 60 itens onde AMBOS os símbolos-alvo estão presentes nas 9 opções
  // ====================================================================================================
  { id: 'n2-B1-001', block: 'B1', targets: ['plus', 'square'], choices: ['tee', 'square', 'circleX', 'perp', 'uArc', 'wave', 'arc', 'plus', 'angle'], answerIndices: [1, 7] },
  { id: 'n2-B1-002', block: 'B1', targets: ['circle', 'diamond'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'diamond', 'arc', 'angle', 'circle'], answerIndices: [5, 8] },
  { id: 'n2-B1-003', block: 'B1', targets: ['zigzag', 'arrow'], choices: ['arrow', 'plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag'], answerIndices: [0, 8] },
  { id: 'n2-B1-004', block: 'B1', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'tee', 'ell'], answerIndices: [7, 8] },
  { id: 'n2-B1-005', block: 'B1', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'uArc', 'arc'], answerIndices: [7, 8] },
  { id: 'n2-B1-006', block: 'B1', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'circleX', 'wave'], answerIndices: [7, 8] },
  { id: 'n2-B1-007', block: 'B1', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'plus', 'angle'], answerIndices: [7, 8] },
  { id: 'n2-B1-008', block: 'B1', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'circle', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-009', block: 'B1', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [7, 8] },
  { id: 'n2-B1-010', block: 'B1', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'ell', 'arrow'], answerIndices: [7, 8] },
  { id: 'n2-B1-011', block: 'B1', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'arc', 'tee'], answerIndices: [7, 8] },
  { id: 'n2-B1-012', block: 'B1', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'wave', 'uArc'], answerIndices: [7, 8] },
  { id: 'n2-B1-013', block: 'B1', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circleX'], answerIndices: [7, 8] },
  { id: 'n2-B1-014', block: 'B1', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circle', 'plus'], answerIndices: [7, 8] },
  { id: 'n2-B1-015', block: 'B1', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'perp', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-016', block: 'B1', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'arrow', 'zigzag'], answerIndices: [7, 8] },
  { id: 'n2-B1-017', block: 'B1', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'tee', 'ell'], answerIndices: [7, 8] },
  { id: 'n2-B1-018', block: 'B1', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'uArc', 'arc'], answerIndices: [7, 8] },
  { id: 'n2-B1-019', block: 'B1', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'circleX', 'wave'], answerIndices: [7, 8] },
  { id: 'n2-B1-020', block: 'B1', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'plus', 'angle'], answerIndices: [7, 8] },
  { id: 'n2-B1-021', block: 'B1', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'circle', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-022', block: 'B1', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [7, 8] },
  { id: 'n2-B1-023', block: 'B1', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'ell', 'arrow'], answerIndices: [7, 8] },
  { id: 'n2-B1-024', block: 'B1', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'arc', 'tee'], answerIndices: [7, 8] },
  { id: 'n2-B1-025', block: 'B1', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'wave', 'uArc'], answerIndices: [7, 8] },
  { id: 'n2-B1-026', block: 'B1', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circleX'], answerIndices: [7, 8] },
  { id: 'n2-B1-027', block: 'B1', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circle', 'plus'], answerIndices: [7, 8] },
  { id: 'n2-B1-028', block: 'B1', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'perp', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-029', block: 'B1', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'arrow', 'zigzag'], answerIndices: [7, 8] },
  { id: 'n2-B1-030', block: 'B1', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'tee', 'ell'], answerIndices: [7, 8] },
  { id: 'n2-B1-031', block: 'B1', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'uArc', 'arc'], answerIndices: [7, 8] },
  { id: 'n2-B1-032', block: 'B1', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'circleX', 'wave'], answerIndices: [7, 8] },
  { id: 'n2-B1-033', block: 'B1', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'plus', 'angle'], answerIndices: [7, 8] },
  { id: 'n2-B1-034', block: 'B1', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'circle', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-035', block: 'B1', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [7, 8] },
  { id: 'n2-B1-036', block: 'B1', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'ell', 'arrow'], answerIndices: [7, 8] },
  { id: 'n2-B1-037', block: 'B1', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'arc', 'tee'], answerIndices: [7, 8] },
  { id: 'n2-B1-038', block: 'B1', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'wave', 'uArc'], answerIndices: [7, 8] },
  { id: 'n2-B1-039', block: 'B1', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circleX'], answerIndices: [7, 8] },
  { id: 'n2-B1-040', block: 'B1', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circle', 'plus'], answerIndices: [7, 8] },
  { id: 'n2-B1-041', block: 'B1', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'perp', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-042', block: 'B1', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'arrow', 'zigzag'], answerIndices: [7, 8] },
  { id: 'n2-B1-043', block: 'B1', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'tee', 'ell'], answerIndices: [7, 8] },
  { id: 'n2-B1-044', block: 'B1', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'uArc', 'arc'], answerIndices: [7, 8] },
  { id: 'n2-B1-045', block: 'B1', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'circleX', 'wave'], answerIndices: [7, 8] },
  { id: 'n2-B1-046', block: 'B1', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'plus', 'angle'], answerIndices: [7, 8] },
  { id: 'n2-B1-047', block: 'B1', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'circle', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-048', block: 'B1', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [7, 8] },
  { id: 'n2-B1-049', block: 'B1', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'ell', 'arrow'], answerIndices: [7, 8] },
  { id: 'n2-B1-050', block: 'B1', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'arc', 'tee'], answerIndices: [7, 8] },
  { id: 'n2-B1-051', block: 'B1', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'wave', 'uArc'], answerIndices: [7, 8] },
  { id: 'n2-B1-052', block: 'B1', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circleX'], answerIndices: [7, 8] },
  { id: 'n2-B1-053', block: 'B1', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'circle', 'plus'], answerIndices: [7, 8] },
  { id: 'n2-B1-054', block: 'B1', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'perp', 'square'], answerIndices: [7, 8] },
  { id: 'n2-B1-055', block: 'B1', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'arrow', 'zigzag'], answerIndices: [7, 8] },
  { id: 'n2-B1-056', block: 'B1', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'tee', 'ell'], answerIndices: [7, 8] },
  { id: 'n2-B1-057', block: 'B1', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'uArc', 'arc'], answerIndices: [7, 8] },
  { id: 'n2-B1-058', block: 'B1', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'circleX', 'wave'], answerIndices: [7, 8] },
  { id: 'n2-B1-059', block: 'B1', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'plus', 'angle'], answerIndices: [7, 8] },
  { id: 'n2-B1-060', block: 'B1', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'circle', 'square'], answerIndices: [7, 8] },
    { id: 'n2-B1-061', block: 'B1', targets: ['diamond', 'triangle'], choices: ['diamond', 'chevronUp', 'star', 'triangleRight', 'hash', 'ellipse', 'triangle', 'pentagon', 'cross'], answerIndices: [0, 6] },
  { id: 'n2-B1-062', block: 'B1', targets: ['triangleDown', 'triangleLeft'], choices: ['hexagon', 'equal', 'heart', 'chevronRight', 'triangleDown', 'moon', 'hash', 'ellipse', 'triangleLeft'], answerIndices: [4, 8] },
  { id: 'n2-B1-063', block: 'B1', targets: ['triangleRight', 'pentagon'], choices: ['star', 'triangleRight', 'chevronDown', 'cross', 'bracketLeft', 'hourglass', 'chevronUp', 'pentagon', 'infinity'], answerIndices: [1, 7] },
  { id: 'n2-B1-064', block: 'B1', targets: ['hexagon', 'star'], choices: ['chevronLeft', 'triangle', 'ellipse', 'hexagon', 'hash', 'star', 'bowtie', 'equal', 'diamond'], answerIndices: [3, 5] },
  { id: 'n2-B1-065', block: 'B1', targets: ['cross', 'equal'], choices: ['pentagon', 'triangleLeft', 'cross', 'chevronRight', 'ellipse', 'triangleDown', 'hourglass', 'notEqual', 'equal'], answerIndices: [2, 8] },
  { id: 'n2-B1-066', block: 'B1', targets: ['notEqual', 'hash'], choices: ['notEqual', 'triangleRight', 'bolt', 'star', 'hash', 'triangle', 'chevronDown', 'bracketRight', 'moon'], answerIndices: [0, 4] },
  { id: 'n2-B1-067', block: 'B1', targets: ['chevronUp', 'chevronDown'], choices: ['ellipse', 'chevronDown', 'triangle', 'hourglass', 'equal', 'bowtie', 'chevronUp', 'hexagon', 'bracketLeft'], answerIndices: [1, 6] },
  { id: 'n2-B1-068', block: 'B1', targets: ['chevronLeft', 'chevronRight'], choices: ['equal', 'star', 'chevronRight', 'triangleLeft', 'heart', 'infinity', 'bowtie', 'chevronLeft', 'diamond'], answerIndices: [2, 7] },
  { id: 'n2-B1-069', block: 'B1', targets: ['bracketLeft', 'bracketRight'], choices: ['triangleDown', 'pentagon', 'hash', 'bracketLeft', 'triangleRight', 'chevronUp', 'bracketRight', 'ellipse', 'cross'], answerIndices: [3, 6] },
  { id: 'n2-B1-070', block: 'B1', targets: ['bolt', 'heart'], choices: ['triangle', 'chevronLeft', 'bracketRight', 'bolt', 'triangleLeft', 'star', 'heart', 'hourglass', 'pentagon'], answerIndices: [3, 6] },
  { id: 'n2-B1-071', block: 'B1', targets: ['moon', 'infinity'], choices: ['hash', 'triangleRight', 'chevronUp', 'equal', 'moon', 'star', 'chevronDown', 'infinity', 'ellipse'], answerIndices: [4, 7] },
  { id: 'n2-B1-072', block: 'B1', targets: ['hourglass', 'bowtie'], choices: ['triangleLeft', 'hourglass', 'pentagon', 'diamond', 'bowtie', 'triangleDown', 'cross', 'bracketLeft', 'hexagon'], answerIndices: [1, 4] },
  { id: 'n2-B1-073', block: 'B1', targets: ['trapezoid', 'ellipse'], choices: ['triangle', 'hash', 'trapezoid', 'chevronRight', 'ellipse', 'bolt', 'chevronUp', 'equal', 'heart'], answerIndices: [2, 4] },
  { id: 'n2-B1-074', block: 'B1', targets: ['diamond', 'triangleLeft'], choices: ['diamond', 'hourglass', 'chevronDown', 'star', 'hash', 'pentagon', 'infinity', 'ellipse', 'triangleLeft'], answerIndices: [0, 8] },
  { id: 'n2-B1-075', block: 'B1', targets: ['star', 'pentagon'], choices: ['chevronRight', 'triangleRight', 'bracketLeft', 'star', 'bolt', 'triangle', 'pentagon', 'equal', 'moon'], answerIndices: [3, 6] },
  { id: 'n2-B1-076', block: 'B1', targets: ['hexagon', 'triangleRight'], choices: ['bracketRight', 'triangleRight', 'ellipse', 'triangleDown', 'hash', 'hexagon', 'heart', 'chevronLeft', 'notEqual'], answerIndices: [1, 5] },
  { id: 'n2-B1-077', block: 'B1', targets: ['cross', 'notEqual'], choices: ['triangle', 'cross', 'chevronUp', 'star', 'notEqual', 'diamond', 'hourglass', 'hash', 'trapezoid'], answerIndices: [1, 4] },
  { id: 'n2-B1-078', block: 'B1', targets: ['equal', 'hash'], choices: ['triangleLeft', 'ellipse', 'equal', 'moon', 'hash', 'chevronRight', 'bowtie', 'bracketLeft', 'pentagon'], answerIndices: [2, 4] },
  { id: 'n2-B1-079', block: 'B1', targets: ['chevronUp', 'chevronRight'], choices: ['chevronUp', 'pentagon', 'bracketRight', 'diamond', 'ellipse', 'triangle', 'chevronRight', 'equal', 'heart'], answerIndices: [0, 6] },
  { id: 'n2-B1-080', block: 'B1', targets: ['chevronDown', 'chevronLeft'], choices: ['triangleRight', 'chevronDown', 'hash', 'cross', 'bracketLeft', 'pentagon', 'chevronLeft', 'bowtie', 'triangle'], answerIndices: [1, 6] },
  { id: 'n2-B1-081', block: 'B1', targets: ['bracketLeft', 'bolt'], choices: ['chevronUp', 'hexagon', 'bracketLeft', 'star', 'bolt', 'ellipse', 'triangleDown', 'notEqual', 'trapezoid'], answerIndices: [2, 4] },
  { id: 'n2-B1-082', block: 'B1', targets: ['bracketRight', 'heart'], choices: ['cross', 'pentagon', 'triangleLeft', 'bracketRight', 'hash', 'heart', 'equal', 'chevronDown', 'moon'], answerIndices: [3, 5] },
  { id: 'n2-B1-083', block: 'B1', targets: ['moon', 'hourglass'], choices: ['triangleRight', 'hash', 'moon', 'chevronLeft', 'star', 'hourglass', 'diamond', 'ellipse', 'chevronUp'], answerIndices: [2, 5] },
  { id: 'n2-B1-084', block: 'B1', targets: ['infinity', 'bowtie'], choices: ['infinity', 'triangle', 'heart', 'equal', 'bowtie', 'hexagon', 'chevronRight', 'bracketLeft', 'trapezoid'], answerIndices: [0, 4] },
  { id: 'n2-B1-085', block: 'B1', targets: ['trapezoid', 'diamond'], choices: ['ellipse', 'triangleDown', 'trapezoid', 'hash', 'triangleRight', 'diamond', 'star', 'notEqual', 'chevronDown'], answerIndices: [2, 5] },
  { id: 'n2-B1-086', block: 'B1', targets: ['ellipse', 'triangle'], choices: ['triangle', 'chevronUp', 'equal', 'ellipse', 'bracketRight', 'bowtie', 'hexagon', 'heart', 'bracketLeft'], answerIndices: [0, 3] },
  { id: 'n2-B1-087', block: 'B1', targets: ['triangleDown', 'star'], choices: ['triangleLeft', 'triangleDown', 'chevronRight', 'ellipse', 'hash', 'star', 'bolt', 'infinity', 'cross'], answerIndices: [1, 5] },
  { id: 'n2-B1-088', block: 'B1', targets: ['pentagon', 'equal'], choices: ['pentagon', 'bracketLeft', 'triangle', 'moon', 'equal', 'chevronUp', 'diamond', 'chevronLeft', 'hourglass'], answerIndices: [0, 4] },
  { id: 'n2-B1-089', block: 'B1', targets: ['hexagon', 'hash'], choices: ['hexagon', 'ellipse', 'triangleRight', 'trapezoid', 'hash', 'infinity', 'chevronDown', 'star', 'bowtie'], answerIndices: [0, 4] },
  { id: 'n2-B1-090', block: 'B1', targets: ['chevronLeft', 'bracketLeft'], choices: ['chevronLeft', 'triangle', 'diamond', 'star', 'bracketLeft', 'equal', 'pentagon', 'cross', 'ellipse'], answerIndices: [0, 4] },
  { id: 'n2-B1-091', block: 'B1', targets: ['chevronRight', 'bracketRight'], choices: ['triangleDown', 'chevronRight', 'heart', 'hash', 'ellipse', 'bracketRight', 'hourglass', 'triangleLeft', 'notEqual'], answerIndices: [1, 5] },
  { id: 'n2-B1-092', block: 'B1', targets: ['bolt', 'infinity'], choices: ['triangleRight', 'bolt', 'pentagon', 'ellipse', 'infinity', 'hash', 'chevronUp', 'star', 'bracketLeft'], answerIndices: [1, 4] },
  { id: 'n2-B1-093', block: 'B1', targets: ['heart', 'trapezoid'], choices: ['heart', 'triangle', 'equal', 'chevronDown', 'trapezoid', 'diamond', 'chevronLeft', 'moon', 'cross'], answerIndices: [0, 4] },
  { id: 'n2-B1-094', block: 'B1', targets: ['moon', 'triangleLeft'], choices: ['moon', 'chevronRight', 'bracketRight', 'star', 'hash', 'triangleLeft', 'ellipse', 'triangle', 'pentagon'], answerIndices: [0, 5] },
  { id: 'n2-B1-095', block: 'B1', targets: ['hourglass', 'triangleRight'], choices: ['equal', 'triangleRight', 'bowtie', 'hourglass', 'diamond', 'chevronUp', 'bracketLeft', 'cross', 'infinity'], answerIndices: [1, 3] },
  { id: 'n2-B1-096', block: 'B1', targets: ['bowtie', 'diamond'], choices: ['bowtie', 'ellipse', 'chevronDown', 'triangle', 'diamond', 'hash', 'heart', 'pentagon', 'bracketRight'], answerIndices: [0, 4] },
  { id: 'n2-B1-097', block: 'B1', targets: ['ellipse', 'equal'], choices: ['star', 'triangleLeft', 'ellipse', 'bolt', 'equal', 'triangleRight', 'notEqual', 'chevronLeft', 'hourglass'], answerIndices: [2, 4] },
  { id: 'n2-B1-098', block: 'B1', targets: ['notEqual', 'star'], choices: ['infinity', 'notEqual', 'pentagon', 'chevronUp', 'star', 'triangle', 'hash', 'heart', 'bracketRight'], answerIndices: [1, 4] },
  { id: 'n2-B1-099', block: 'B1', targets: ['cross', 'chevronUp'], choices: ['cross', 'triangleRight', 'ellipse', 'bracketLeft', 'chevronUp', 'equal', 'trapezoid', 'bowtie', 'diamond'], answerIndices: [0, 4] },
  { id: 'n2-B1-100', block: 'B1', targets: ['chevronDown', 'pentagon'], choices: ['triangle', 'chevronDown', 'heart', 'ellipse', 'hash', 'pentagon', 'bracketRight', 'infinity', 'star'], answerIndices: [1, 5] },

  // ====================================================================================================
  // BLOCO 2: 60 itens onde APENAS 1 dos símbolos-alvo está presente nas 9 opções
  // ====================================================================================================
  { id: 'n2-B2-001', block: 'B2', targets: ['plus', 'square'], choices: ['tee', 'circleX', 'perp', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-002', block: 'B2', targets: ['circle', 'perp'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [8] },
  { id: 'n2-B2-003', block: 'B2', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'arrow'], answerIndices: [8] },
  { id: 'n2-B2-004', block: 'B2', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'tee'], answerIndices: [8] },
  { id: 'n2-B2-005', block: 'B2', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'uArc'], answerIndices: [8] },
  { id: 'n2-B2-006', block: 'B2', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'circleX'], answerIndices: [8] },
  { id: 'n2-B2-007', block: 'B2', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-008', block: 'B2', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-009', block: 'B2', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'zigzag'], answerIndices: [8] },
  { id: 'n2-B2-010', block: 'B2', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [8] },
  { id: 'n2-B2-011', block: 'B2', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'arc'], answerIndices: [8] },
  { id: 'n2-B2-012', block: 'B2', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'wave'], answerIndices: [8] },
  { id: 'n2-B2-013', block: 'B2', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'angle'], answerIndices: [8] },
  { id: 'n2-B2-014', block: 'B2', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-015', block: 'B2', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'perp'], answerIndices: [8] },
  { id: 'n2-B2-016', block: 'B2', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'arrow'], answerIndices: [8] },
  { id: 'n2-B2-017', block: 'B2', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'tee'], answerIndices: [8] },
  { id: 'n2-B2-018', block: 'B2', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'uArc'], answerIndices: [8] },
  { id: 'n2-B2-019', block: 'B2', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'circleX'], answerIndices: [8] },
  { id: 'n2-B2-020', block: 'B2', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-021', block: 'B2', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-022', block: 'B2', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'zigzag'], answerIndices: [8] },
  { id: 'n2-B2-023', block: 'B2', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [8] },
  { id: 'n2-B2-024', block: 'B2', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'arc'], answerIndices: [8] },
  { id: 'n2-B2-025', block: 'B2', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'wave'], answerIndices: [8] },
  { id: 'n2-B2-026', block: 'B2', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'angle'], answerIndices: [8] },
  { id: 'n2-B2-027', block: 'B2', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-028', block: 'B2', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'perp'], answerIndices: [8] },
  { id: 'n2-B2-029', block: 'B2', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'arrow'], answerIndices: [8] },
  { id: 'n2-B2-030', block: 'B2', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'tee'], answerIndices: [8] },
  { id: 'n2-B2-031', block: 'B2', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'uArc'], answerIndices: [8] },
  { id: 'n2-B2-032', block: 'B2', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'circleX'], answerIndices: [8] },
  { id: 'n2-B2-033', block: 'B2', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-034', block: 'B2', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-035', block: 'B2', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'zigzag'], answerIndices: [8] },
  { id: 'n2-B2-036', block: 'B2', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [8] },
  { id: 'n2-B2-037', block: 'B2', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'arc'], answerIndices: [8] },
  { id: 'n2-B2-038', block: 'B2', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'wave'], answerIndices: [8] },
  { id: 'n2-B2-039', block: 'B2', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'angle'], answerIndices: [8] },
  { id: 'n2-B2-040', block: 'B2', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-041', block: 'B2', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'perp'], answerIndices: [8] },
  { id: 'n2-B2-042', block: 'B2', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'arrow'], answerIndices: [8] },
  { id: 'n2-B2-043', block: 'B2', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'tee'], answerIndices: [8] },
  { id: 'n2-B2-044', block: 'B2', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'uArc'], answerIndices: [8] },
  { id: 'n2-B2-045', block: 'B2', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'circleX'], answerIndices: [8] },
  { id: 'n2-B2-046', block: 'B2', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-047', block: 'B2', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-048', block: 'B2', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'zigzag'], answerIndices: [8] },
  { id: 'n2-B2-049', block: 'B2', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [8] },
  { id: 'n2-B2-050', block: 'B2', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'arc'], answerIndices: [8] },
  { id: 'n2-B2-051', block: 'B2', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'wave'], answerIndices: [8] },
  { id: 'n2-B2-052', block: 'B2', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'angle'], answerIndices: [8] },
  { id: 'n2-B2-053', block: 'B2', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
  { id: 'n2-B2-054', block: 'B2', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'perp'], answerIndices: [8] },
  { id: 'n2-B2-055', block: 'B2', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'arrow'], answerIndices: [8] },
  { id: 'n2-B2-056', block: 'B2', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'tee'], answerIndices: [8] },
  { id: 'n2-B2-057', block: 'B2', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'uArc'], answerIndices: [8] },
  { id: 'n2-B2-058', block: 'B2', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'circleX'], answerIndices: [8] },
  { id: 'n2-B2-059', block: 'B2', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'plus'], answerIndices: [8] },
  { id: 'n2-B2-060', block: 'B2', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'circle'], answerIndices: [8] },
   { id: 'n2-B2-061', block: 'B2', targets: ['diamond', 'triangle'], choices: ['diamond', 'chevronUp', 'star', 'triangleRight', 'hash', 'ellipse', 'pentagon', 'cross', 'hexagon'], answerIndices: [0] },
  { id: 'n2-B2-062', block: 'B2', targets: ['triangleDown', 'triangleLeft'], choices: ['hexagon', 'equal', 'heart', 'chevronRight', 'triangleDown', 'moon', 'hash', 'ellipse', 'star'], answerIndices: [4] },
  { id: 'n2-B2-063', block: 'B2', targets: ['triangleRight', 'pentagon'], choices: ['star', 'triangleRight', 'chevronDown', 'cross', 'bracketLeft', 'hourglass', 'chevronUp', 'diamond', 'infinity'], answerIndices: [1] },
  { id: 'n2-B2-064', block: 'B2', targets: ['hexagon', 'star'], choices: ['chevronLeft', 'triangle', 'ellipse', 'hexagon', 'hash', 'bowtie', 'equal', 'diamond', 'bracketRight'], answerIndices: [3] },
  { id: 'n2-B2-065', block: 'B2', targets: ['cross', 'equal'], choices: ['pentagon', 'triangleLeft', 'cross', 'chevronRight', 'ellipse', 'triangleDown', 'hourglass', 'notEqual', 'hash'], answerIndices: [2] },
  { id: 'n2-B2-066', block: 'B2', targets: ['notEqual', 'hash'], choices: ['notEqual', 'triangleRight', 'bolt', 'star', 'triangle', 'chevronDown', 'bracketRight', 'moon', 'ellipse'], answerIndices: [0] },
  { id: 'n2-B2-067', block: 'B2', targets: ['chevronUp', 'chevronDown'], choices: ['ellipse', 'triangle', 'hourglass', 'equal', 'bowtie', 'chevronUp', 'hexagon', 'bracketLeft', 'heart'], answerIndices: [5] },
  { id: 'n2-B2-068', block: 'B2', targets: ['chevronLeft', 'chevronRight'], choices: ['equal', 'star', 'triangleLeft', 'heart', 'infinity', 'bowtie', 'chevronLeft', 'diamond', 'bracketRight'], answerIndices: [6] },
  { id: 'n2-B2-069', block: 'B2', targets: ['bracketLeft', 'bracketRight'], choices: ['triangleDown', 'pentagon', 'hash', 'triangleRight', 'chevronUp', 'bracketRight', 'ellipse', 'cross', 'star'], answerIndices: [5] },
  { id: 'n2-B2-070', block: 'B2', targets: ['bolt', 'heart'], choices: ['triangle', 'chevronLeft', 'bracketRight', 'bolt', 'triangleLeft', 'star', 'hourglass', 'pentagon', 'infinity'], answerIndices: [3] },
  { id: 'n2-B2-071', block: 'B2', targets: ['moon', 'infinity'], choices: ['hash', 'triangleRight', 'chevronUp', 'equal', 'moon', 'star', 'chevronDown', 'ellipse', 'bracketLeft'], answerIndices: [4] },
  { id: 'n2-B2-072', block: 'B2', targets: ['hourglass', 'bowtie'], choices: ['triangleLeft', 'pentagon', 'diamond', 'bowtie', 'triangleDown', 'cross', 'bracketLeft', 'hexagon', 'chevronRight'], answerIndices: [3] },
  { id: 'n2-B2-073', block: 'B2', targets: ['trapezoid', 'ellipse'], choices: ['triangle', 'hash', 'trapezoid', 'chevronRight', 'bolt', 'chevronUp', 'equal', 'heart', 'infinity'], answerIndices: [2] },
  { id: 'n2-B2-074', block: 'B2', targets: ['diamond', 'triangleLeft'], choices: ['diamond', 'hourglass', 'chevronDown', 'star', 'hash', 'pentagon', 'infinity', 'ellipse', 'triangleRight'], answerIndices: [0] },
  { id: 'n2-B2-075', block: 'B2', targets: ['star', 'pentagon'], choices: ['chevronRight', 'triangleRight', 'bracketLeft', 'star', 'bolt', 'triangle', 'equal', 'moon', 'hash'], answerIndices: [3] },
  { id: 'n2-B2-076', block: 'B2', targets: ['hexagon', 'triangleRight'], choices: ['bracketRight', 'ellipse', 'triangleDown', 'hash', 'hexagon', 'heart', 'chevronLeft', 'notEqual', 'star'], answerIndices: [4] },
  { id: 'n2-B2-077', block: 'B2', targets: ['cross', 'notEqual'], choices: ['triangle', 'cross', 'chevronUp', 'star', 'diamond', 'hourglass', 'hash', 'trapezoid', 'ellipse'], answerIndices: [1] },
  { id: 'n2-B2-078', block: 'B2', targets: ['equal', 'hash'], choices: ['triangleLeft', 'ellipse', 'moon', 'equal', 'chevronRight', 'bowtie', 'bracketLeft', 'pentagon', 'heart'], answerIndices: [3] },
  { id: 'n2-B2-079', block: 'B2', targets: ['chevronUp', 'chevronRight'], choices: ['pentagon', 'bracketRight', 'diamond', 'ellipse', 'triangle', 'chevronRight', 'equal', 'heart', 'bowtie'], answerIndices: [5] },
  { id: 'n2-B2-080', block: 'B2', targets: ['chevronDown', 'chevronLeft'], choices: ['triangleRight', 'chevronDown', 'hash', 'cross', 'bracketLeft', 'pentagon', 'bowtie', 'triangle', 'ellipse'], answerIndices: [1] },
  { id: 'n2-B2-081', block: 'B2', targets: ['bracketLeft', 'bolt'], choices: ['chevronUp', 'hexagon', 'star', 'bolt', 'ellipse', 'triangleDown', 'notEqual', 'trapezoid', 'moon'], answerIndices: [3] },
  { id: 'n2-B2-082', block: 'B2', targets: ['bracketRight', 'heart'], choices: ['cross', 'pentagon', 'triangleLeft', 'hash', 'heart', 'equal', 'chevronDown', 'moon', 'diamond'], answerIndices: [4] },
  { id: 'n2-B2-083', block: 'B2', targets: ['moon', 'hourglass'], choices: ['triangleRight', 'hash', 'chevronLeft', 'star', 'hourglass', 'diamond', 'ellipse', 'chevronUp', 'bracketRight'], answerIndices: [4] },
  { id: 'n2-B2-084', block: 'B2', targets: ['infinity', 'bowtie'], choices: ['triangle', 'heart', 'equal', 'bowtie', 'hexagon', 'chevronRight', 'bracketLeft', 'trapezoid', 'hash'], answerIndices: [3] },
  { id: 'n2-B2-085', block: 'B2', targets: ['trapezoid', 'diamond'], choices: ['ellipse', 'triangleDown', 'hash', 'triangleRight', 'trapezoid', 'star', 'notEqual', 'chevronDown', 'bracketRight'], answerIndices: [4] },
  { id: 'n2-B2-086', block: 'B2', targets: ['ellipse', 'triangle'], choices: ['chevronUp', 'equal', 'bolt', 'ellipse', 'bowtie', 'hexagon', 'heart', 'bracketLeft', 'star'], answerIndices: [3] },
  { id: 'n2-B2-087', block: 'B2', targets: ['triangleDown', 'star'], choices: ['triangleLeft', 'chevronRight', 'ellipse', 'hash', 'star', 'bolt', 'infinity', 'cross', 'moon'], answerIndices: [4] },
  { id: 'n2-B2-088', block: 'B2', targets: ['pentagon', 'equal'], choices: ['bracketLeft', 'triangle', 'moon', 'equal', 'chevronUp', 'diamond', 'chevronLeft', 'hourglass', 'notEqual'], answerIndices: [3] },
  { id: 'n2-B2-089', block: 'B2', targets: ['hexagon', 'hash'], choices: ['ellipse', 'triangleRight', 'trapezoid', 'hexagon', 'infinity', 'chevronDown', 'star', 'bowtie', 'bracketLeft'], answerIndices: [3] },
  { id: 'n2-B2-090', block: 'B2', targets: ['chevronLeft', 'bracketLeft'], choices: ['triangle', 'diamond', 'star', 'bracketLeft', 'equal', 'pentagon', 'cross', 'ellipse', 'chevronUp'], answerIndices: [3] },
  { id: 'n2-B2-091', block: 'B2', targets: ['chevronRight', 'bracketRight'], choices: ['triangleDown', 'heart', 'hash', 'ellipse', 'bracketRight', 'hourglass', 'triangleLeft', 'notEqual', 'pentagon'], answerIndices: [4] },
  { id: 'n2-B2-092', block: 'B2', targets: ['bolt', 'infinity'], choices: ['triangleRight', 'pentagon', 'ellipse', 'infinity', 'hash', 'chevronUp', 'star', 'bracketLeft', 'triangle'], answerIndices: [3] },
  { id: 'n2-B2-093', block: 'B2', targets: ['heart', 'trapezoid'], choices: ['triangle', 'equal', 'chevronDown', 'trapezoid', 'diamond', 'chevronLeft', 'moon', 'cross', 'bracketRight'], answerIndices: [3] },
  { id: 'n2-B2-094', block: 'B2', targets: ['moon', 'triangleLeft'], choices: ['chevronRight', 'bracketRight', 'star', 'hash', 'triangleLeft', 'ellipse', 'triangle', 'pentagon', 'hourglass'], answerIndices: [4] },
  { id: 'n2-B2-095', block: 'B2', targets: ['hourglass', 'triangleRight'], choices: ['equal', 'bowtie', 'hourglass', 'diamond', 'chevronUp', 'bracketLeft', 'cross', 'infinity', 'heart'], answerIndices: [2] },
  { id: 'n2-B2-096', block: 'B2', targets: ['bowtie', 'diamond'], choices: ['ellipse', 'chevronDown', 'triangle', 'diamond', 'hash', 'heart', 'pentagon', 'bracketRight', 'chevronLeft'], answerIndices: [3] },
  { id: 'n2-B2-097', block: 'B2', targets: ['ellipse', 'equal'], choices: ['triangleLeft', 'ellipse', 'bolt', 'equal', 'triangleRight', 'notEqual', 'chevronLeft', 'hourglass', 'bracketLeft'], answerIndices: [1] },
  { id: 'n2-B2-098', block: 'B2', targets: ['notEqual', 'star'], choices: ['infinity', 'pentagon', 'chevronUp', 'star', 'triangle', 'hash', 'heart', 'bracketRight', 'diamond'], answerIndices: [3] },
  { id: 'n2-B2-099', block: 'B2', targets: ['cross', 'chevronUp'], choices: ['triangleRight', 'ellipse', 'bracketLeft', 'chevronUp', 'equal', 'trapezoid', 'bowtie', 'diamond', 'hash'], answerIndices: [3] },
  { id: 'n2-B2-100', block: 'B2', targets: ['chevronDown', 'pentagon'], choices: ['triangle', 'chevronDown', 'heart', 'ellipse', 'hash', 'bracketRight', 'infinity', 'star', 'bowtie'], answerIndices: [1] },

  // ====================================================================================================
  // BLOCO 3: 60 itens onde NENHUM dos símbolos-alvo está presente nas 9 opções
  // ====================================================================================================
  { id: 'n2-B3-001', block: 'B3', targets: ['plus', 'square'], choices: ['tee', 'circleX', 'perp', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-002', block: 'B3', targets: ['circle', 'perp'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-003', block: 'B3', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-004', block: 'B3', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [] },
  { id: 'n2-B3-005', block: 'B3', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-006', block: 'B3', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-007', block: 'B3', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-008', block: 'B3', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-009', block: 'B3', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-010', block: 'B3', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'perp'], answerIndices: [] },
  { id: 'n2-B3-011', block: 'B3', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-012', block: 'B3', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-013', block: 'B3', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-014', block: 'B3', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-015', block: 'B3', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-016', block: 'B3', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-017', block: 'B3', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [] },
  { id: 'n2-B3-018', block: 'B3', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-019', block: 'B3', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-020', block: 'B3', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-021', block: 'B3', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-022', block: 'B3', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-023', block: 'B3', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'perp'], answerIndices: [] },
  { id: 'n2-B3-024', block: 'B3', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-025', block: 'B3', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-026', block: 'B3', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-027', block: 'B3', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-028', block: 'B3', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-029', block: 'B3', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-030', block: 'B3', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [] },
  { id: 'n2-B3-031', block: 'B3', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-032', block: 'B3', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-033', block: 'B3', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-034', block: 'B3', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-035', block: 'B3', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-036', block: 'B3', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'perp'], answerIndices: [] },
  { id: 'n2-B3-037', block: 'B3', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-038', block: 'B3', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-039', block: 'B3', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-040', block: 'B3', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-041', block: 'B3', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-042', block: 'B3', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-043', block: 'B3', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [] },
  { id: 'n2-B3-044', block: 'B3', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-045', block: 'B3', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-046', block: 'B3', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-047', block: 'B3', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-048', block: 'B3', targets: ['perp', 'zigzag'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-049', block: 'B3', targets: ['arrow', 'ell'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'perp'], answerIndices: [] },
  { id: 'n2-B3-050', block: 'B3', targets: ['tee', 'arc'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-051', block: 'B3', targets: ['uArc', 'wave'], choices: ['plus', 'square', 'tee', 'circleX', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-052', block: 'B3', targets: ['circleX', 'angle'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-053', block: 'B3', targets: ['plus', 'circle'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-054', block: 'B3', targets: ['square', 'perp'], choices: ['plus', 'tee', 'uArc', 'wave', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-055', block: 'B3', targets: ['zigzag', 'arrow'], choices: ['plus', 'square', 'tee', 'uArc', 'wave', 'arc', 'angle', 'circle', 'ell'], answerIndices: [] },
  { id: 'n2-B3-056', block: 'B3', targets: ['ell', 'tee'], choices: ['plus', 'square', 'circleX', 'uArc', 'wave', 'arc', 'angle', 'zigzag', 'perp'], answerIndices: [] },
  { id: 'n2-B3-057', block: 'B3', targets: ['arc', 'uArc'], choices: ['plus', 'square', 'tee', 'circleX', 'wave', 'perp', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-058', block: 'B3', targets: ['wave', 'circleX'], choices: ['plus', 'square', 'tee', 'uArc', 'perp', 'arc', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-059', block: 'B3', targets: ['angle', 'plus'], choices: ['square', 'tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-060', block: 'B3', targets: ['square', 'circle'], choices: ['tee', 'uArc', 'wave', 'perp', 'arc', 'circleX', 'angle', 'zigzag', 'ell'], answerIndices: [] },
  { id: 'n2-B3-061', block: 'B3', targets: ['diamond', 'triangle'], choices: ['chevronUp', 'star', 'triangleRight', 'hash', 'ellipse', 'pentagon', 'cross', 'hexagon', 'equal'], answerIndices: [] },
  { id: 'n2-B3-062', block: 'B3', targets: ['triangleDown', 'triangleLeft'], choices: ['hexagon', 'equal', 'heart', 'chevronRight', 'moon', 'hash', 'ellipse', 'star', 'infinity'], answerIndices: [] },
  { id: 'n2-B3-063', block: 'B3', targets: ['triangleRight', 'pentagon'], choices: ['star', 'chevronDown', 'cross', 'bracketLeft', 'hourglass', 'chevronUp', 'diamond', 'infinity', 'ellipse'], answerIndices: [] },
  { id: 'n2-B3-064', block: 'B3', targets: ['hexagon', 'star'], choices: ['chevronLeft', 'triangle', 'ellipse', 'hash', 'bowtie', 'equal', 'diamond', 'bracketRight', 'heart'], answerIndices: [] },
  { id: 'n2-B3-065', block: 'B3', targets: ['cross', 'equal'], choices: ['pentagon', 'triangleLeft', 'chevronRight', 'ellipse', 'triangleDown', 'hourglass', 'notEqual', 'hash', 'bracketLeft'], answerIndices: [] },
  { id: 'n2-B3-066', block: 'B3', targets: ['notEqual', 'hash'], choices: ['triangleRight', 'bolt', 'star', 'triangle', 'chevronDown', 'bracketRight', 'moon', 'ellipse', 'heart'], answerIndices: [] },
  { id: 'n2-B3-067', block: 'B3', targets: ['chevronUp', 'chevronDown'], choices: ['ellipse', 'triangle', 'hourglass', 'equal', 'bowtie', 'hexagon', 'bracketLeft', 'heart', 'diamond'], answerIndices: [] },
  { id: 'n2-B3-068', block: 'B3', targets: ['chevronLeft', 'chevronRight'], choices: ['equal', 'star', 'triangleLeft', 'heart', 'infinity', 'bowtie', 'diamond', 'bracketRight', 'moon'], answerIndices: [] },
  { id: 'n2-B3-069', block: 'B3', targets: ['bracketLeft', 'bracketRight'], choices: ['triangleDown', 'pentagon', 'hash', 'triangleRight', 'chevronUp', 'ellipse', 'cross', 'star', 'hexagon'], answerIndices: [] },
  { id: 'n2-B3-070', block: 'B3', targets: ['bolt', 'heart'], choices: ['triangle', 'chevronLeft', 'bracketRight', 'triangleLeft', 'star', 'hourglass', 'pentagon', 'infinity', 'ellipse'], answerIndices: [] },
  { id: 'n2-B3-071', block: 'B3', targets: ['moon', 'infinity'], choices: ['hash', 'triangleRight', 'chevronUp', 'equal', 'star', 'chevronDown', 'ellipse', 'bracketLeft', 'bolt'], answerIndices: [] },
  { id: 'n2-B3-072', block: 'B3', targets: ['hourglass', 'bowtie'], choices: ['triangleLeft', 'pentagon', 'diamond', 'triangleDown', 'cross', 'bracketLeft', 'hexagon', 'chevronRight', 'heart'], answerIndices: [] },
  { id: 'n2-B3-073', block: 'B3', targets: ['trapezoid', 'ellipse'], choices: ['triangle', 'hash', 'chevronRight', 'bolt', 'chevronUp', 'equal', 'heart', 'infinity', 'star'], answerIndices: [] },
  { id: 'n2-B3-074', block: 'B3', targets: ['diamond', 'triangleLeft'], choices: ['hourglass', 'chevronDown', 'star', 'hash', 'pentagon', 'infinity', 'ellipse', 'triangleRight', 'cross'], answerIndices: [] },
  { id: 'n2-B3-075', block: 'B3', targets: ['star', 'pentagon'], choices: ['chevronRight', 'triangleRight', 'bracketLeft', 'bolt', 'triangle', 'equal', 'moon', 'hash', 'ellipse'], answerIndices: [] },
  { id: 'n2-B3-076', block: 'B3', targets: ['hexagon', 'triangleRight'], choices: ['bracketRight', 'ellipse', 'triangleDown', 'hash', 'heart', 'chevronLeft', 'notEqual', 'star', 'diamond'], answerIndices: [] },
  { id: 'n2-B3-077', block: 'B3', targets: ['cross', 'notEqual'], choices: ['triangle', 'chevronUp', 'star', 'diamond', 'hourglass', 'hash', 'trapezoid', 'ellipse', 'infinity'], answerIndices: [] },
  { id: 'n2-B3-078', block: 'B3', targets: ['equal', 'hash'], choices: ['triangleLeft', 'ellipse', 'moon', 'chevronRight', 'bowtie', 'bracketLeft', 'pentagon', 'heart', 'triangle'], answerIndices: [] },
  { id: 'n2-B3-079', block: 'B3', targets: ['chevronUp', 'chevronRight'], choices: ['pentagon', 'bracketRight', 'diamond', 'ellipse', 'triangle', 'equal', 'heart', 'bowtie', 'hash'], answerIndices: [] },
  { id: 'n2-B3-080', block: 'B3', targets: ['chevronDown', 'chevronLeft'], choices: ['triangleRight', 'hash', 'cross', 'bracketLeft', 'pentagon', 'bowtie', 'triangle', 'ellipse', 'infinity'], answerIndices: [] },
  { id: 'n2-B3-081', block: 'B3', targets: ['bracketLeft', 'bolt'], choices: ['chevronUp', 'hexagon', 'star', 'ellipse', 'triangleDown', 'notEqual', 'trapezoid', 'moon', 'heart'], answerIndices: [] },
  { id: 'n2-B3-082', block: 'B3', targets: ['bracketRight', 'heart'], choices: ['cross', 'pentagon', 'triangleLeft', 'hash', 'equal', 'chevronDown', 'moon', 'diamond', 'infinity'], answerIndices: [] },
  { id: 'n2-B3-083', block: 'B3', targets: ['moon', 'hourglass'], choices: ['triangleRight', 'hash', 'chevronLeft', 'star', 'diamond', 'ellipse', 'chevronUp', 'bracketRight', 'heart'], answerIndices: [] },
  { id: 'n2-B3-084', block: 'B3', targets: ['infinity', 'bowtie'], choices: ['triangle', 'heart', 'equal', 'hexagon', 'chevronRight', 'bracketLeft', 'trapezoid', 'hash', 'cross'], answerIndices: [] },
  { id: 'n2-B3-085', block: 'B3', targets: ['trapezoid', 'diamond'], choices: ['ellipse', 'triangleDown', 'hash', 'triangleRight', 'star', 'notEqual', 'chevronDown', 'bracketRight', 'cross'], answerIndices: [] },
  { id: 'n2-B3-086', block: 'B3', targets: ['ellipse', 'triangle'], choices: ['chevronUp', 'equal', 'bolt', 'bowtie', 'hexagon', 'heart', 'bracketLeft', 'star', 'hash'], answerIndices: [] },
  { id: 'n2-B3-087', block: 'B3', targets: ['triangleDown', 'star'], choices: ['triangleLeft', 'chevronRight', 'ellipse', 'hash', 'bolt', 'infinity', 'cross', 'moon', 'bracketLeft'], answerIndices: [] },
  { id: 'n2-B3-088', block: 'B3', targets: ['pentagon', 'equal'], choices: ['bracketLeft', 'triangle', 'moon', 'chevronUp', 'diamond', 'chevronLeft', 'hourglass', 'notEqual', 'star'], answerIndices: [] },
  { id: 'n2-B3-089', block: 'B3', targets: ['hexagon', 'hash'], choices: ['ellipse', 'triangleRight', 'trapezoid', 'infinity', 'chevronDown', 'star', 'bowtie', 'bracketLeft', 'equal'], answerIndices: [] },
  { id: 'n2-B3-090', block: 'B3', targets: ['chevronLeft', 'bracketLeft'], choices: ['triangle', 'diamond', 'star', 'equal', 'pentagon', 'cross', 'ellipse', 'chevronUp', 'heart'], answerIndices: [] },
  { id: 'n2-B3-091', block: 'B3', targets: ['chevronRight', 'bracketRight'], choices: ['triangleDown', 'heart', 'hash', 'ellipse', 'hourglass', 'triangleLeft', 'notEqual', 'pentagon', 'cross'], answerIndices: [] },
  { id: 'n2-B3-092', block: 'B3', targets: ['bolt', 'infinity'], choices: ['triangleRight', 'pentagon', 'ellipse', 'hash', 'chevronUp', 'star', 'bracketLeft', 'triangle', 'equal'], answerIndices: [] },
  { id: 'n2-B3-093', block: 'B3', targets: ['heart', 'trapezoid'], choices: ['triangle', 'equal', 'chevronDown', 'diamond', 'chevronLeft', 'moon', 'cross', 'bracketRight', 'hexagon'], answerIndices: [] },
  { id: 'n2-B3-094', block: 'B3', targets: ['moon', 'triangleLeft'], choices: ['chevronRight', 'bracketRight', 'star', 'hash', 'ellipse', 'triangle', 'pentagon', 'hourglass', 'equal'], answerIndices: [] },
  { id: 'n2-B3-095', block: 'B3', targets: ['hourglass', 'triangleRight'], choices: ['equal', 'bowtie', 'diamond', 'chevronUp', 'bracketLeft', 'cross', 'infinity', 'heart', 'hash'], answerIndices: [] },
  { id: 'n2-B3-096', block: 'B3', targets: ['bowtie', 'diamond'], choices: ['chevronDown', 'triangle', 'hash', 'heart', 'pentagon', 'bracketRight', 'chevronLeft', 'ellipse', 'star'], answerIndices: [] },
  { id: 'n2-B3-097', block: 'B3', targets: ['ellipse', 'equal'], choices: ['triangleLeft', 'bolt', 'triangleRight', 'notEqual', 'chevronLeft', 'hourglass', 'bracketLeft', 'star', 'moon'], answerIndices: [] },
  { id: 'n2-B3-098', block: 'B3', targets: ['notEqual', 'star'], choices: ['infinity', 'pentagon', 'chevronUp', 'triangle', 'hash', 'heart', 'bracketRight', 'diamond', 'ellipse'], answerIndices: [] },
  { id: 'n2-B3-099', block: 'B3', targets: ['cross', 'chevronUp'], choices: ['triangleRight', 'ellipse', 'bracketLeft', 'equal', 'trapezoid', 'bowtie', 'diamond', 'hash', 'heart'], answerIndices: [] },
  { id: 'n2-B3-100', block: 'B3', targets: ['chevronDown', 'pentagon'], choices: ['triangle', 'heart', 'ellipse', 'hash', 'bracketRight', 'infinity', 'star', 'bowtie', 'cross'], answerIndices: [] },
];

// Helper para sortear N itens do pool completo
export const getN2Pool = (count) =>
  shuffle(N2_SEQUENCES).slice(0, Math.min(count ?? N2_SEQUENCES.length, N2_SEQUENCES.length));